const menuBtn=document.querySelector('.menu-btn');const navLinks=document.querySelector('.nav-links');menuBtn.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)});document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.querySelectorAll('.filters button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filters button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;document.querySelectorAll('.portfolio-item').forEach(item=>item.classList.toggle('hidden',f!=='all'&&item.dataset.category!==f))}));

const galleries={
 corporate:['assets/corporate.jpg','assets/gallery/corporate-01.jpg','assets/gallery/corporate-02.jpg','assets/gallery/corporate-03.jpg','assets/gallery/corporate-04.jpg','assets/gallery/corporate-05.jpg','assets/gallery/corporate-06.jpg','assets/gallery/corporate-07.jpg'],
 formal:['assets/formal.jpg','assets/gallery/formal-01.jpg','assets/gallery/formal-02.jpg','assets/gallery/formal-03.jpg','assets/gallery/formal-04.jpg','assets/gallery/formal-05.jpg','assets/gallery/formal-06.jpg'],
 private:['assets/private.jpg','assets/gallery/private-01.jpg','assets/gallery/private-02.jpg','assets/gallery/private-03.jpg','assets/gallery/private-04.jpg','assets/gallery/private-05.jpg']
};
const titles={corporate:'Corporate Events',formal:'Formal Events',private:'Private Events'};
const lightbox=document.querySelector('#lightbox'),lightImg=lightbox.querySelector('img'),counter=document.querySelector('#galleryCounter'),galleryTitle=document.querySelector('#galleryTitle');let currentGallery=[],currentIndex=0,touchStartX=0;
function renderGallery(){lightImg.src=currentGallery[currentIndex];counter.textContent=`${currentIndex+1} / ${currentGallery.length}`;}
function moveGallery(step){currentIndex=(currentIndex+step+currentGallery.length)%currentGallery.length;renderGallery();}
document.querySelectorAll('.portfolio-item').forEach(item=>item.addEventListener('click',()=>{const category=item.dataset.category;currentGallery=galleries[category]||[item.dataset.image];currentIndex=0;galleryTitle.textContent=titles[category]||'Our Work';renderGallery();lightbox.showModal()}));
lightbox.querySelector('.gallery-close').addEventListener('click',()=>lightbox.close());lightbox.querySelector('.gallery-prev').addEventListener('click',()=>moveGallery(-1));lightbox.querySelector('.gallery-next').addEventListener('click',()=>moveGallery(1));lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close()});document.addEventListener('keydown',e=>{if(!lightbox.open)return;if(e.key==='ArrowLeft')moveGallery(-1);if(e.key==='ArrowRight')moveGallery(1)});lightbox.addEventListener('touchstart',e=>{touchStartX=e.changedTouches[0].clientX},{passive:true});lightbox.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchStartX;if(Math.abs(dx)>45)moveGallery(dx>0?-1:1)},{passive:true});
const form=document.querySelector('#contactForm'),note=document.querySelector('#formNote');form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form);const subject=encodeURIComponent(`SAS Events enquiry — ${data.get('type')}`);const body=encodeURIComponent(`Name: ${data.get('name')}\nEmail: ${data.get('email')}\nEvent type: ${data.get('type')}\n\n${data.get('message')}`);note.textContent='Opening your email app with the enquiry details…';window.location.href=`mailto:saseventsandservices@gmail.com?subject=${subject}&body=${body}`});document.querySelector('#year').textContent=new Date().getFullYear();
